### PR TITLE
fix(ct): wrong redirect after successful order placement

### LINKED ISSUE #6309: [Checkout] User is not being redirected to ThankYou page after successful order placement
### Expected result
After placing an order, customer should be redirected to Thank You page

### Actual result
!a59317bc-fb01-430a-b136-38814e8cc783|width=83.33333333333334%!

### PR DESCRIPTION
**Pull request by RafalDobrowolski**
## Related Issue

Closes #6309

## How Has This Been Tested?

Automatic e2e tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

#### Changelog
- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.

#### Tests
- [x] I have written test cases for my code
- [ ] I have tested my Pull Request on production build and (to my knowledge) it works without any issues
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

#### Code standards
- [x] My code follows the code style of this project.

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

#### Docs
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/commercetools/theme/middleware/checkout.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
-const canEnterPayment = cart => cart.shippingInfo && cart.shippingAddress;
+const canEnterPayment = cart => cart && cart.shippingInfo && cart.shippingAddress;
```
Comment (dawid-ziobro) [inline packages/commercetools/theme/middleware/checkout.js:1]: This can be shortened to `cart?.shippingInfo` ;)

**Review by dawid-ziobro — APPROVED** [review]

**Review by igorwojciechowski — APPROVED** [review]
