### PR TITLE
fix(ct): add missing pagination for orders history

### LINKED ISSUE #6032: Order History - Customers can only view up to 20 orders in their order history
### Expected result
Customer should be able to view more than just 20 of their orders

### Actual result
Customer can view only up to 20 orders in order history

### Steps to reproduce
1. Login as a customer
1. Place more than 20 orders
1. Go to My Account -> Order History

### PR DESCRIPTION
**Pull request by lukaszjedrasik**
## Description

Implemented pagination for orders history (based on this [PR](https://github.com/vuestorefront/vue-storefront/pull/6108))

## Related Issue

closes #6032 

## Screenshots:

Zrzut ekranu 2021-09-9 o 13 07 14

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

#### Changelog
- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.

#### Tests
- [ ] I have written test cases for my code
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

> I tested manually my code, and it works well with both:
- [ ] Default Theme
- [ ] Capybara Theme

#### Code standards
- [x] My code follows the code style of this project.

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

#### Docs
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by alefbarbeli — APPROVED** [review]

File: packages/commercetools/theme/pages/MyAccount/OrderHistory.vue [hunk 1]
```diff
@@ -0,0 +1,287 @@
...
+    const limit = 10;
+    const { orders, search } = useUserOrder();
+    const currentOrder = ref(null);
+
+    onSSR(async () => {
+      await search({ limit, offset: 0, sort: 'createdAt desc' });
+    });
+
+    const goNext = (offset) => {
+      search({ limit, offset: offset + limit, sort: 'createdAt desc' });
```
Comment (dawid-ziobro) [inline packages/commercetools/theme/pages/MyAccount/OrderHistory.vue:140]: Didn't want you to create single method that'll accept direction (prev/next) as a param to search for items? Then you could use it here, in `goPrev` and on init

**Review by igorwojciechowski — APPROVED** [review]

**Review by dawid-ziobro — APPROVED** [review]
