### PR TITLE
fix(ct): add a copy of the whole product obj in enhanceProduct

### LINKED ISSUE #6405: include a copy of the product object in enhanceProduct helper
When using custom queries for the getProduct call some fields don't get mapped to the returned products variable by useProduct composable. We need access to all of them.

### PR DESCRIPTION
**Pull request by MarcinSulowski**
## Description
When using custom queries for the getProduct call some fields don't get mapped to the returned products variable by useProduct composable. This PR solves this issue by making it possible to access all the requested fields under the _original key.

## Related Issue
closes #6405

#6405

## How Has This Been Tested?
Tested locally with an exiting project, run tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

#### Changelog
- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.

#### Tests
- [ ] I have written test cases for my code
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

> I tested manually my code, and it works well with both:
- [ ] Default Theme
- [ ] Capybara Theme

#### Code standards
- [x] My code follows the code style of this project.

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

#### Docs
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/commercetools/composables/src/helpers/internals/enhanceProduct.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ const enhanceProduct = (productResponse: ApolloQueryResult<ProductData>, context
         _description: current.description,
         _categoriesRef: current.categoriesRef.map((cr) => cr.id),
         _rating: (product as any).reviewRatingStatistics,
-        ...(product.productType && { _productType: product.productType })
+        _original: product
```
Comment (dawid-ziobro) [inline packages/commercetools/composables/src/helpers/internals/enhanceProduct.ts:41]: `productType` is no longer needed?

**Review by RafalDobrowolski — APPROVED** [review]

File: packages/commercetools/composables/src/helpers/internals/enhanceProduct.ts (hunk 1 above)
Comment (MarcinSulowski) [reply packages/commercetools/composables/src/helpers/internals/enhanceProduct.ts:41]: @dawid-ziobro not really, since from now on any custom field (like productType) can be found in the _original obj
Screenshot 2021-10-01 at 17 47 24
.
