### PR TITLE
fix: hydration error on category page in desktop mode

### LINKED ISSUE #5744: Next: entering category page in SSR break the app
## Current behavior
Connected with [EN-156](https://vsf.atlassian.net/browse/EN-156?atlOrigin=eyJpIjoiMmQxYWZiNDEzZjE1NDFlY2I3NTg3MmIzMGQ3YmNlMGUiLCJwIjoiaiJ9)
Entering category page shows error in console:
image

## Expected behavior
No error appearing.

## Steps to reproduce the issue
1. Enter https://demo-enterprise.europe-west1.gcp.storefrontcloud.io/c/women 
2. See the error in console  

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

### PR DESCRIPTION
**Pull request by AdamPawlinski**
### Related Issues
closes #5744 

### Short Description of the PR
Fixes hydration error on category page in desktop mode. 
It's temporary solution, because it need to be fixed in SFUI by changing the wrapping div in SfIcon. It is a part of SfMenuItem and it causes html syntax bug - div inside button.  
There's an issue to resolve this problem in SFUI - [#1766](https://github.com/vuestorefront/storefront-ui/issues/1766)

However it looks like there is an error in mobile mode in HeaderNavigationItem, which I couldn't solve:
image

But it only appears in dev mode.  

### Screenshots of Visual Changes before/after (if There Are Any)

Category page after fixing:

image

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [ ] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [ ] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

### CODE REVIEW

**Review by andrzejewsky — APPROVED** [review]

File: packages/core/nuxt-theme-module/theme/components/AppHeader.vue [hunk 1]
```diff
@@ -12,8 +12,30 @@
...
+                &#8203;
+              </template>
+            </SfMenuItem>
+          </template>
+        </SfHeaderNavigationItem>
+        <SfHeaderNavigationItem class="nav-item"  data-cy="app-header-url_men" label="MEN" :link="localePath('/c/men')" >
+          <template #mobile-navigation-item>
+            <SfMenuItem label="MEN" class="sf-header-navigation-item__menu-item">
+              <template #mobile-nav-icon>
+                &#8203;
```
Comment (andrzejewsky) [inline packages/core/nuxt-theme-module/theme/components/AppHeader.vue:34]: do we really need to do such a hack? I think that should be fixed in SFUI

Comment (AdamPawlinski) [reply packages/core/nuxt-theme-module/theme/components/AppHeader.vue:34]: yes for sure, but it is temporary solution to make it work

File: packages/core/docs/changelog/5744.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+  description: 'Fix hydration bug on category page',
+  link: 'https://github.com/vuestorefront/vue-storefront/issues/5744',
+  isBreaking: false,
+  breakingChanges: [
+    {
+      module: 'affected module',
+      before: 'how it was',
+      after: 'how it is',
+      comment: 'quick migration guide'
+    }
```
Comment (filrak) [inline packages/core/docs/changelog/5744.js:11]:
```suggestion
```

**Review by filrak — CHANGES_REQUESTED** [review]
