### PR TITLE
fix: Add missing `i18n` tags 

### LINKED ISSUE #5337: Add missing `i18n` tags
Add missing `i18n` tags and translations in next theme

https://i18n.nuxtjs.org/basic-usage/

### PR DESCRIPTION
**Pull request by justyna-13**
### Related Issues

closes #5337 

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: packages/core/nuxt-theme-module/theme/components/MyAccount/ProfileUpdateForm.vue [hunk 1]
```diff
@@ -1,5 +1,5 @@
 <template>
-  <b>Please implement vendor specific ProfileUpdateForm component in 'components/MyAccount' directory</b>
+  <b>{{ $t('Please implement vendor specific ProfileUpdateForm') }}</b>
```
Comment (filrak) [inline packages/core/nuxt-theme-module/theme/components/MyAccount/ProfileUpdateForm.vue:2]: I think we can omit prompts like this since they're just for developers, I'll mark them in comments with 🥥

File: packages/core/nuxt-theme-module/theme/components/MyAccount/PasswordResetForm.vue [hunk 2]
```diff
@@ -1,5 +1,5 @@
 <template>
-  <b>Please implement vendor specific PasswordResetForm component in 'components/MyAccount' directory</b>
+  <b>{{ $t('Please implement vendor specific PasswordResetForm') }}</b>
```
Comment (filrak) [inline packages/core/nuxt-theme-module/theme/components/MyAccount/PasswordResetForm.vue:2]: 🥥

File: packages/core/nuxt-theme-module/theme/components/MyAccount/BillingAddressForm.vue [hunk 3]
```diff
@@ -1,5 +1,5 @@
 <template>
-  <b>Please implement vendor specific BillingAddressForm component in 'components/MyAccount' directory</b>
+  <b>{{ $t('Please implement vendor specific BillingAddressForm') }}</b>
```
Comment (filrak) [inline packages/core/nuxt-theme-module/theme/components/MyAccount/BillingAddressForm.vue:2]: 🥥

File: packages/core/nuxt-theme-module/theme/components/UserBillingAddress.vue [hunk 4]
```diff
@@ -1,5 +1,5 @@
 <template>
-  <b>Please implement vendor specific UserBillingAddress component in 'components' directory</b>
+  <b>{{ $t('Implement vendor specific UserBillingAddress component') }}</b>
```
Comment (filrak) [inline packages/core/nuxt-theme-module/theme/components/UserBillingAddress.vue:2]: 🥥

File: packages/core/nuxt-theme-module/theme/components/UserShippingAddress.vue [hunk 5]
```diff
@@ -1,5 +1,5 @@
 <template>
-  <b>Please implement vendor specific UserShippingAddress component in 'components' directory</b>
+  <b>{{ $t('Implement vendor specific UserShippingAddress component') }}</b>
```
Comment (filrak) [inline packages/core/nuxt-theme-module/theme/components/UserShippingAddress.vue:2]: 🥥

File: packages/core/nuxt-theme-module/theme/pages/MyAccount/OrderHistory.vue [hunk 6]
```diff
@@ -72,18 +71,23 @@
...
+              </SfButton>
             </SfTableData>
           </SfTableRow>
         </SfTable>
       </div>
     </SfTab>
     <SfTab data-cy="order-history-tab_returns" title="Returns">
       <p class="message">
-        This feature is not implemented yet! Please take a look at<br />
+        {{ $t('Feature is not implemented') }}
```
Comment (filrak) [inline packages/core/nuxt-theme-module/theme/pages/MyAccount/OrderHistory.vue:87]: 🥥

File: packages/core/nuxt-theme-module/theme/pages/MyAccount/OrderHistory.vue [hunk 7]
```diff
@@ -72,18 +71,23 @@
...
+        <br />
         <SfLink class="message__link" href="#">https://github.com/DivanteLtd/vue-storefront/issues</SfLink>
-         for our Roadmap!
+        {{ $t('For our Roadmap') }}
```
Comment (filrak) [inline packages/core/nuxt-theme-module/theme/pages/MyAccount/OrderHistory.vue:90]: 🥥

**Review by filrak — CHANGES_REQUESTED** [review]

**Review by filrak — APPROVED** [review]
