### PR TITLE
fix(ct): fix no property error in useUser/changePassword

### LINKED ISSUE #6231: [MyAccount / ChangePassword] no `logOut` property in useUser/changePassword
!image-20210824-123749.png|width=100%!

### PR DESCRIPTION
**Pull request by igorwojciechowski**
## Description

Fixes no `logOut` property in `useUser` composable in `changePassword` function

## Related Issue

Closes #6231

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.

#### Changelog
- [ ] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.

#### Tests
- [ ] I have written test cases for my code
- [ ] I have tested my Pull Request on production build and (to my knowledge) it works without any issues
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

> I tested manually my code, and it works well with both:
- [ ] Default Theme
- [ ] Capybara Theme

#### Code standards
- [ ] My code follows the code style of this project.

- [ ] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

#### Docs
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/commercetools/composables/src/useUser/factoryParams.ts [hunk 1]
```diff
@@ -60,7 +60,7 @@ export const useUserFactoryParams: UseUserFactoryParams<Customer, any, any> = {
     const loadedUser = await getCurrentUser(context, currentUser, customQuery);
     const userResponse = await context.$ct.api.customerChangeMyPassword(loadedUser.version, currentPassword, newPassword);
     // we do need to re-authenticate user to acquire new token - otherwise all subsequent requests will fail as unauthorized
-    await this.logOut(context);
+    await useUserFactoryParams.logOut(context, { currentUser });
```
Comment (filipsobol) [inline packages/commercetools/composables/src/useUser/factoryParams.ts:63]: `logOut` only accepts one parameter - `context`.

**Review by filipsobol — CHANGES_REQUESTED** [review]

File: packages/core/docs/core/changelog/6231.js [hunk 2]
```diff
@@ -0,0 +1,8 @@
+module.exports = {
+  description: 'Change `logOut` function signature in useUserFactory - `params` is now optional',
```
Comment (filipsobol) [inline packages/core/docs/core/changelog/6231.js:2]:
```suggestion
  description: 'Make parameters in the `useUser.logOut` method optional',
```

**Review by filipsobol — APPROVED** [review]
