### PR TITLE
Draft: Totals localstorage sync

### LINKED ISSUE #4733: Wrong grand total in cart if cart gets manipulated by different browser tabs. (same session, sync works only partial)
## Current behavior

Grand Total is wrong in browser tab 1 if user adds product in browser tab 2 (same session). The cart list of products gets synced but grand total not. (Side note: In https://vsf-next-demo.storefrontcloud.io/ the cart sync between browser tabs seems not to work at all)

## Expected behavior

Micro Cart (including grand total) should be always in sync and same state in all browser tabs.

## Steps to reproduce the issue

1. Add product to cart. f.e. this one https://demo.vuestorefront.io/didi-sport-watch.html

2. Open new browser tab, then open Micro cart. Everything looks fine.

3. Change cart by changing quantity or adding another product from PDP in one of the browser tabs.

4. Product list gets synced to the other browser tab session. Grand total stays old and is therefore wrong.

## Repository
https://demo.vuestorefront.io/

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome, latest version
- OS: IOS
- Node: https://demo.storefrontcloud.io
- Code Version: https://demo.storefrontcloud.io

### PR DESCRIPTION
**Pull request by Fifciu**
### Related Issues

closes #4733

### Short Description and Why It's Useful

Currently, we are synchronizing the current cart between carts using localStorage. In this PR, I've implemented the same for Totals.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [ ] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: core/modules/cart/helpers/totalsCacheHandler.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import * as types from '../store/mutation-types'
+import { Logger } from '@vue-storefront/core/lib/logger'
+
+import { StorageManager } from '@vue-storefront/core/lib/storage-manager'
+
+export const totalsCacheHandlerFactory = (mutation, state) => {
```
Comment (gibkigonzo) [inline core/modules/cart/helpers/totalsCacheHandler.ts:6]: it's not a factory 🤔 Can you change name? Its misleading

Comment (gibkigonzo) [reply core/modules/cart/helpers/totalsCacheHandler.ts:6]: Or change it to `export const totalsCacheHandlerFactory = () => (mutation, state) => {`? `cartCacheHandlerFactory` also shouldn't be factory. We are passing there global object as parameter 😕and its not even used

File: core/modules/cart/store/actions/totalsActions.ts [hunk 2]
```diff
@@ -10,6 +10,9 @@ import {
 import EventBus from '@vue-storefront/core/compatibility/plugins/event-bus'
 
 const totalsActions = {
+  async syncTotalsWhenLocalStorageChange ({ commit }, payload) {
```
Comment (gibkigonzo) [inline core/modules/cart/store/actions/totalsActions.ts:13]: wdyt about just `updateTotals` or something similar? I understand the context where it's used, but it just updates totals 🤷I think it doesn't need to have such a specific name

File: core/modules/cart/helpers/totalsCacheHandler.ts (hunk 1 above)
Comment (Fifciu) [reply core/modules/cart/helpers/totalsCacheHandler.ts:6]: I am going to make it `cartCacheHandlerPlugin` and `totalsCacheHandlerPlugin`

Comment (Fifciu) [reply core/modules/cart/helpers/totalsCacheHandler.ts:6]: And get rid of this `(Vue) => {}` part from `cartCacheHandlerFactory`

File: core/modules/cart/store/actions/totalsActions.ts (hunk 2 above)
Comment (Fifciu) [reply core/modules/cart/store/actions/totalsActions.ts]: Done. I did same for updateCart

**Review by gibkigonzo — APPROVED** [review]
