### PR TITLE
Unicode alpha field validation

### LINKED ISSUE #5340: UnicodeAlpha field validation not working properly
## Current behavior

Field validation passes when any character from field value is a unicode alpha char. 
"%%" does not pass validation, which is the expected behaviour:

However, "Jo$%n Do?" validates correctly:

## Expected behavior

If string has **any** special characters it should not validate

## Steps to reproduce the issue

* Go to checkout
* Write a name with one or more correct alpha characters and with one or more incorrect special characters

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: Chrome 87.0.4280.88
* OS: Mac OS 10.13.6
* Node: v10.16.3
* Code Version: Develop

### PR DESCRIPTION
**Pull request by lukaszjedrasik**
### Related Issues

closes #5340 

### Short Description and Why It's Useful
I have changed regex in unicodeAlpha validator helper and added some tests.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature
- [ ] (Next only) I've followed this [instruction](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and I've created a `.js` file with information about my Pull Request

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: core/helpers/validators/index.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
...
+export const unicodeAlpha = (value: string): boolean => /^[a-zA-Z_ ]*$/.test(value)
```
Comment (Fifciu) [inline core/helpers/validators/index.ts:2]: It is not a proper solution. In the example for the issue, Pablo gave validation for name as an example. Your regex will not pass name with special chars, e.g. it won't pass `Łukasz` because of `Ł`. Old one solved this issue but also allowed for chars like $. 

The target is to support names with special chars (like `Łukasz`) but prevent chars like `$`

**Review by Fifciu — CHANGES_REQUESTED** [review]

File: core/helpers/validators/index.ts (hunk 1 above)
Comment (lukaszjedrasik) [reply core/helpers/validators/index.ts]: Fixed

File: core/helpers/validators/index.ts [hunk 2]
```diff
@@ -1,5 +1,5 @@
...
+export const unicodeAlpha = (value: string): boolean => /^[a-zA-ZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİıĲĳĴĵĶķĸĹĺĻļĽľŁłĿŀŃńŅņŇňŉŊŋŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽžſ_ ]*$/.test(value)
```
Comment (Fifciu) [inline core/helpers/validators/index.ts:2]: Why do we have `_` here?

**Review by Fifciu — CHANGES_REQUESTED** [review]
Look well. Please just get rid of this `_`. Another thing I recommend doing is write unit tests for these 2 validators

File: core/helpers/test/unit/validators/unicodeAlphaNum.spec.ts [hunk 3]
```diff
@@ -0,0 +1,15 @@
+import { unicodeAlphaNum } from '../../../validators';
+
+describe('unicodeAlphaNum', () => {
+  it('returns true if string contains any unicode alphabet characters or digits', () => {
+    const exampleValue = unicodeAlphaNum('Xyz 123');
```
Comment (Fifciu) [inline core/helpers/test/unit/validators/unicodeAlphaNum.spec.ts:5]: You should add more advanced cases. Like from the test above + numbers

**Review by Fifciu — CHANGES_REQUESTED** [review]

**Review by Fifciu — APPROVED** [review]

**Comment by Fifciu** [comment]
Good job thx
