### PR TITLE
Bug/graphql querying

### LINKED ISSUE #5692: Category/Middleware API :: GraphQL error on querying products with limit of >=165
## Environment
**host:** localhost
**branch:** next

## Expected result
When querying for products with limit of more than 164 products, the middlware should either respond with data of requested products or at least handle the exception if query indeed is too complex - 

## Actual result
GraphQL error is thrown; middleware API does not respond with any response; Category page freezes

## Steps to reproduce
With web proxy

1. Turn on network traffic intercepting on web proxy
1. Go to Category page
1. Tamper request data for /api/ct/getProduct call -> change `limit:20` to `limit:165`
1. Send the request

With API client

```json
POST /api/ct/getProduct HTTP/1.1
Host: localhost:3000
Content-Length: 84
sec-ch-ua: "Chromium";v="89", ";Not A Brand";v="99"
Accept: application/json, text/plain, */*
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Content-Type: application/json;charset=UTF-8
Origin: http://localhost:3000
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:3000/c/women
Accept-Encoding: gzip, deflate
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: vsf-locale=en; vsf-commercetools-token=%7B%22access_token%22%3A%22<token>%22%2C%22token_type%22%3A%22Bearer%22%2C%22expires_in%22%3A172713%2C%22scope%22%3A%22manage_products%3Avsf-ct-dev%20create_anonymous_token%3Avsf-ct-dev%20manage_my_profile%3Avsf-ct-dev%20manage_customer_groups%3Avsf-ct-dev%20view_products%3Avsf-ct-dev%20view_customer_groups%3Avsf-ct-dev%20view_categories%3Avsf-ct-dev%20introspect_oauth_tokens%3Avsf-ct-dev%20manage_my_payments%3Avsf-ct-dev%20manage_my_orders%3Avsf-ct-dev%20manage_my_shopping_lists%3Avsf-ct-dev%20view_published_products%3Avsf-ct-dev%22%2C%22expires_at%22%3A1616605244386%7D
Connection: close

[
  {
    "catId":"<cartId>",
    "limit":165,
    "offset":0,
    "filters":[
    ]
  }
]
```

## Screenshots
!graphql-error.PNG|width=100%!

### LINKED ISSUE #5693: Product/Middleware API :: Missing error handling for incorrect product id
## Expected result
Middleware responds with `404 Not Found` response (or other adequate); response contains error message

## Actual result
API does not respond with any response; GraphQL error is being thrown

## Request
```java
POST /api/ct/getProduct HTTP/1.1
Host: localhost:3000
Content-Length: 20
sec-ch-ua: "Chromium";v="89", ";Not A Brand";v="99"
Accept: application/json, text/plain, */*
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Content-Type: application/json;charset=UTF-8
Origin: http://localhost:3000
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:3000/p/38143c0c-c9b0-448c-93cd-60eb90d8da57/aspesi-shirt-h805-white
Accept-Encoding: gzip, deflate
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: vsf-locale=en; vsf-commercetools-token=%7B%22access_token%22%3A%22<token>%22%2C%22token_type%22%3A%22Bearer%22%2C%22expires_in%22%3A172713%2C%22scope%22%3A%22manage_products%3Avsf-ct-dev%20create_anonymous_token%3Avsf-ct-dev%20manage_my_profile%3Avsf-ct-dev%20manage_customer_groups%3Avsf-ct-dev%20view_products%3Avsf-ct-dev%20view_customer_groups%3Avsf-ct-dev%20view_categories%3Avsf-ct-dev%20introspect_oauth_tokens%3Avsf-ct-dev%20manage_my_payments%3Avsf-ct-dev%20manage_my_orders%3Avsf-ct-dev%20manage_my_shopping_lists%3Avsf-ct-dev%20view_published_products%3Avsf-ct-dev%22%2C%22expires_at%22%3A1616605244386%7D
Connection: close

[
  {
    "id":"test"
  },
  null
]
```

## Console output
`ERROR  [VSF][error] [GraphQL error]: Message: Malformed parameter: where: Invalid UUID string: test, Location: [column: 3, line: 73], Path: products`

### PR DESCRIPTION
**Pull request by Baroshem**
### Related Issues

closes #5692 
closes #5693

### Short Description of the PR

Correctly throw error when GraphQL query is over the complexity limit. Error is thrown in integration (Commercetools) and can be handled/displayed to the user later if needed.

### Screenshots of Visual Changes before/after (if There Are Any)

5692
image

5693
image

### Pull Request Checklist

- [ ] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [ ] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

### CODE REVIEW

**Review by andrzejewsky — APPROVED** [review]

File: packages/commercetools/api-client/src/api/getProduct/index.ts [hunk 1]
```diff
@@ -26,14 +26,19 @@ const getProduct = async (context, params, customQuery?: CustomQuery) => {
...
+    const request = await (context.client as ApolloClient<any>).query<ProductData>({
+      query: gql`${products.query}`,
+      variables: products.variables,
+      // temporary, seems like bug in apollo:
+      // @link: https://github.com/apollographql/apollo-client/issues/3234
+      fetchPolicy: 'no-cache'
+    });
+    return request;
+  } catch (error) {
+    throw error.graphQLErrors?.[0] || error.networkError?.result || error;
```
Comment (Fifciu) [inline packages/commercetools/api-client/src/api/getProduct/index.ts:39]: What does this try...catch it give us?

Comment (Baroshem) [reply packages/commercetools/api-client/src/api/getProduct/index.ts:39]: Whole try catch allows us to catch an error that is thrown by GraphQL in the terminal but is not handled on the client side. This strange looking throw catches different parts of the error for different problems. The problem with GrapQL query limit is thrown in the NetworkError object of error, while bug with product id lives in GraphQLErrors. Normally it would only throw an error property or the whole error object, but here, with one change two problems can be fixed as they relate to each other.

**Review by Fifciu — APPROVED** [review]
