### PR TITLE
fix: Order history pagination

### LINKED ISSUE #4599: Order History Pagination Not Working Properly
## Current behavior

**Issue** : While viewing order history, the user can not see more than 20 orders.

**Why its not working** : lazyLoadOrdersOnScroll implemented on the order history page, calls getOrdersHistory,
which previously used to fetch all the orders, but on introducing pagination support in "getOrdersHistory", it only fetches 20 orders, which is its default value. 
Still, the order history page calls it only once, trying to fetch all the results, and on those results, it applies lazyLoadOrdersOnScroll.

Due to which the user can not see more than 20 orders. 

## Expected behavior

User should be able to see all the orders while scrolling through the order history page.

## Steps to reproduce the issue

1. Login with a valid user having more than 20 orders.
1. Go to profile.
1. Click on order history.
1. Scroll down to view more orders.

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

### PR DESCRIPTION
**Pull request by lukaszjedrasik**
### Related Issues

closes #4599 

### Short Description of the PR

- Fixed pagination support (user can see more than 20 orders)
- Added new user action `appendOrdersHistory` + unit test
- Showed 10 orders at the start instead 11

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- I tested manually my code and it works well with both:
- [x] Default Theme
- [x] Capybara Theme
- [x] I have written test cases for my code

- [ ] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

### CODE REVIEW

File: core/modules/order/components/UserOrdersHistory.ts [hunk 1]
```diff
@@ -18,14 +18,19 @@ export default {
...
       return items
     }
   },
   methods: {
     onBottomScroll () {
-      ++this.pagination.current
+      const totalCount = this.$store.state.user.orders_history.total_count ? this.$store.state.user.orders_history.total_count : 0;
+      const isLastPage = this.pagination.current > Math.ceil(totalCount / this.pagination.perPage);
+      if (!isLastPage) {
+        ++this.pagination.current;
```
Comment (Fifciu) [inline core/modules/order/components/UserOrdersHistory.ts:31]:
```suggestion
        this.pagination.current++;
```

File: core/modules/user/store/actions.ts [hunk 2]
```diff
@@ -269,6 +270,19 @@ const actions: ActionTree<UserState, RootState> = {
...
+    const resp = await UserService.getOrdersHistory(pageSize, currentPage)
+
+    if (resp.code === 200) {
+      const oldOrders = getters.getOrdersHistory;
+      let orders = resp.result;
+      if (oldOrders && orders.items) orders.items = uniqBy([...oldOrders, ...orders.items], 'increment_id')
+
+      commit(types.USER_ORDERS_HISTORY_LOADED, orders)
+      EventBus.$emit('user-after-loaded-orders', orders)
+      return orders
```
Comment (Fifciu) [inline core/modules/user/store/actions.ts:283]: Please use `expect` for these 2 lines as you did above

File: core/modules/user/test/unit/store/actions.spec.ts [hunk 3]
```diff
@@ -456,6 +456,31 @@ describe('User actions', () => {
...
+
+      await (userActions as any).appendOrdersHistory(contextMock, {
+        pageSize,
+        currentPage
+      })
+
+      expect(contextMock.commit).toBeCalledWith(types.USER_ORDERS_HISTORY_LOADED, responseOb.result);
+    })
+  })
+
```
Comment (Fifciu) [inline core/modules/user/test/unit/store/actions.spec.ts:483]: I would also test if merged `oldOrders` with `order.items` are really unique.

**Review by Fifciu — CHANGES_REQUESTED** [review]

File: core/modules/user/test/unit/store/actions.spec.ts [hunk 4]
```diff
@@ -456,6 +456,73 @@ describe('User actions', () => {
...
+        pageSize,
+        currentPage
+      })
+
+      expect(contextMock.commit).toBeCalledWith(types.USER_ORDERS_HISTORY_LOADED, responseOb.result);
+      expect(EventBus.$emit).toBeCalledWith('user-after-loaded-orders', result);
+      expect(result).toBe(responseOb.result)
+    })
+
+    it('returns unique orders', async () => {
```
Comment (Fifciu) [inline core/modules/user/test/unit/store/actions.spec.ts:485]:
```suggestion
    it('returns orders with unique increment_id', async () => {
```

**Review by Fifciu — APPROVED** [review]
