### PR TITLE
fix(OS-169): allow to customise currency & country cookie names

### LINKED ISSUE #6296: Allow the possibility of modifying the default i18n cookie names via nuxt.config.js
Currently the default i18n cookie names (VSF_LOCALE_COOKIE, VSF_CURRENCY_COOKIE, etc.) are defined in the core as constants, and there’s no way to change them. We can only change the cookie names in the integration’s config (ctx.$integration.config.cookies) via nuxt.config.js, but this won’t override the values set in the core which makes this feature pointless.

**Expected result**

Providing cookie name config in nuxt.config.js changes not only the cookie names in our integration's config object from useVSFContext, but also overrides the default values set in the core

### PR DESCRIPTION
**Pull request by MarcinSulowski**
## Description
Currently VSF_LOCALE_COOKIE and VSF_CURRENCY_COOKIE are defined in the core as constants and used by the i18nCookiesPlugin to set the corresponding values with no possibility of overriding their names. This PR makes it possible to change their names via nuxt.config.js

`
i18n: {
    ....
    cookies: {
      currencyCookieName: 'test-currencyCookieName',
      countryCookieName: 'test-countryCookieName'
    }
`

and middleware.config.js
`
configuration: {
    ....
    cookies: {
      currencyCookieName: 'test-currencyCookieName',
      countryCookieName: 'test-countryCookieName'
    }
`
## Related Issue
Closes #6296

## How Has This Been Tested?

Tested locally in dev and build modes, cookie names get set as specified in configuration.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

#### Changelog
- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.

#### Tests
- [ ] I have written test cases for my code
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

> I tested manually my code, and it works well with both:
- [ ] Default Theme
- [ ] Capybara Theme

#### Code standards
- [x] My code follows the code style of this project.

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

#### Docs
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/core/nuxt-module/lib/plugins/i18n-cookies.js [hunk 1]
```diff
@@ -27,8 +27,13 @@ const i18nCookiesPlugin = ({ $cookies }) => {
     expires: new Date(new Date().setFullYear(new Date().getFullYear() + 1)) // Year from now
   };
 
-  !$cookies.get(VSF_CURRENCY_COOKIE) && $cookies.set(VSF_CURRENCY_COOKIE, settings.currency, cookieOptions);
-  !$cookies.get(VSF_COUNTRY_COOKIE) && $cookies.set(VSF_COUNTRY_COOKIE, settings.country, cookieOptions);
+  const cookieNames = {
+    currency: i18n.cookies?.currencyCookieName || VSF_CURRENCY_COOKIE,
```
Comment (dawid-ziobro) [inline packages/core/nuxt-module/lib/plugins/i18n-cookies.js:31]: If it's in `cookies` key, maybe just `currency` and `country` names would be better, will be simpler. WDYT?

**Review by dawid-ziobro — APPROVED** [review]

File: packages/core/nuxt-module/lib/plugins/i18n-cookies.js (hunk 1 above)
Comment (MarcinSulowski) [reply packages/core/nuxt-module/lib/plugins/i18n-cookies.js:31]: @dawid-ziobro I agree, but we already have those keys defined and used in such way in our ct api-client (commercetools/api-client/src/index.server.ts):

`const getI18nConfig = (req, configuration) => {
  const cookieSettings = configuration.cookies || defaultSettings.cookies;
  const { currencyCookieName, countryCookieName, localeCookieName, storeCookieName } = cookieSettings;
  const locale = req.cookies[localeCookieName] || configuration.locale || defaultSettings.locale;
  const currency = req.cookies[currencyCookieName] || configuration.currency || defaultSettings.currency;
  const country = req.cookies[countryCookieName] || configuration.country || defaultSettings.country;
  const store = req.cookies[storeCookieName] || configuration.store;

  return { currency, country, locale, store };
};`

So for the sake of consistency I'd stick with what we have already defined in other places.

Comment (dawid-ziobro) [reply packages/core/nuxt-module/lib/plugins/i18n-cookies.js:31]: Ah ok ;)
