### PR TITLE
Errors handling fix

### LINKED ISSUE #5655: Error handling example in docs and reactivity in composables
## Current behavior

* Error handling example in docs is bad
* Reactivity in composables for errors does not work because we add keys dynamicly

## Expected behavior

* Proper example of error handling in docs
* Reactivity in composables for errors works - let's have initial state of errors and do not add/remove keys

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [x] YES
* [ ] NO

### PR DESCRIPTION
**Pull request by Fifciu**
### Related Issues

closes #5655

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [x] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

### CODE REVIEW

File: packages/core/core/src/factories/useReviewFactory.ts [hunk 1]
```diff
@@ -13,7 +13,10 @@ export function useReviewFactory<REVIEW, REVIEWS_SEARCH_PARAMS, REVIEW_ADD_PARAM
   return function useReview(id: string): UseReview<REVIEW, REVIEWS_SEARCH_PARAMS, REVIEW_ADD_PARAMS> {
     const reviews: Ref<REVIEW> = sharedRef([], `useReviews-reviews-${id}`);
     const loading: Ref<boolean> = sharedRef(false, `useReviews-loading-${id}`);
-    const error: Ref<UseReviewErrors> = sharedRef({}, `useProduct-error-${id}`);
+    const error: Ref<UseReviewErrors> = sharedRef({
+      search: null,
+      addReview: null
```
Comment (Fifciu) [inline packages/core/core/src/factories/useReviewFactory.ts:18]: Did not move errors in methods

File: packages/core/core/src/factories/useWishlistFactory.ts [hunk 2]
```diff
@@ -29,7 +29,12 @@ export const useWishlistFactory = <WISHLIST, WISHLIST_ITEM, PRODUCT>(
     const loading: Ref<boolean> = sharedRef<boolean>(false, 'useWishlist-loading');
     const wishlist: Ref<WISHLIST> = sharedRef(null, 'useWishlist-wishlist');
     const _factoryParams = configureFactoryParams(factoryParams);
-    const error: Ref<UseWishlistErrors> = sharedRef({}, 'useWishlist-error');
+    const error: Ref<UseWishlistErrors> = sharedRef({
+      addItem: null,
+      removeItem: null,
```
Comment (Fifciu) [inline packages/core/core/src/factories/useWishlistFactory.ts:34]: Move errors

**Review by filrak — APPROVED** [review]

**Review by andrzejewsky — APPROVED** [review]
image
