### PR TITLE
Bug #5725/shipping provider loading

### LINKED ISSUE #5725: ShippingProvider shows there are no shipping methods during loading
## Current behavior

ShippingProvider shows there are no shipping methods during loading

## Expected behavior

It should show some loader.

## Steps to reproduce the issue

1. Run app on `next` branch
1. Add smth to the cart
1. Go to the checkout
1. Fill shipping details, and click save
1. Look at ShippingMethodsProvider - it blinks with a paragraph about "No available shipping methods for this address"

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

### PR DESCRIPTION
**Pull request by Baroshem**
### Related Issues

closes #5725 

### Short Description of the PR

Added SfLoader to VsfShippingProvider to correctly handle loading state

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [x] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

### CODE REVIEW

File: packages/commercetools/theme/components/Checkout/VsfShippingProvider.vue [hunk 1]
```diff
@@ -6,15 +6,17 @@
...
+          {{ $t('There was some error while trying to fetch shipping methods. We are sorry, please try with different shipping details or later.') }}
+        </div>
+        <div v-else-if="errorShippingProvider.save">
+          {{ $t('There was some error while trying to select this shipping method. We are sorry, please try with different shipping method or later.') }}
+        </div>
+        <div v-else-if="!shippingMethods.length">
+          {{ $t('There are no shipping methods available for this country. We are sorry, please try with different country or later.') }}
+        </div>
+      </SfLoader>
       <div class="form__radio-group">
```
Comment (filrak) [inline packages/commercetools/theme/components/Checkout/VsfShippingProvider.vue:20]: shouldn't this also be conditionally visible?

Comment (Baroshem) [reply packages/commercetools/theme/components/Checkout/VsfShippingProvider.vue:20]: It wasn't conditionally visible before but I can make it, i.e. create `hasErrors` computed that will return true if there are any errors and add `v-if="hasErrors"` to `SfLoader` and `v-else` to this `div`. What do you think?

**Review by Fifciu — APPROVED** [review]
If you tested it manually and it works fine then I am giving OK

**Review by andrzejewsky — APPROVED** [review]
