### PR TITLE
fix(ct): productType field ommited for custom queries

### LINKED ISSUE #6347: getProduct custom query - productType doesn't get mapped to product response in enhanceProduct helper
In case of extending the product query and trying to get the productType field, the field is omitted in enhanceProduct helper.

### PR DESCRIPTION
**Pull request by MarcinSulowski**
## Description
getProduct custom query - productType field doesn't get mapped to product response in enhanceProduct helper

## Related Issue
closes #6347

#6347

## Motivation and Context
When extending the default product query with a custom query including the productType field, the productType field will not get mapped to the productResponse object.

## How Has This Been Tested?
Tested locally with an exiting project

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

#### Changelog
- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.

#### Tests
- [ ] I have written test cases for my code
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

> I tested manually my code, and it works well with both:
- [ ] Default Theme
- [ ] Capybara Theme

#### Code standards
- [x] My code follows the code style of this project.

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

#### Docs
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/core/docs/changelog/6347.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+module.exports = {
+  description: 'getProduct custom query - productType doesnt get mapped to product response in enhanceProduct helper',
+  link: 'https://github.com/vuestorefront/vue-storefront/issues/6347',
+  isBreaking: false,
+  author: 'Marcin Sulowski',
+  linkToGitHubAccount: 'https://github.com/MarcinSulowski'
+};
```
Comment (filipsobol) [inline packages/core/docs/changelog/6347.js:7]: Because this is commercetools-only change, please move this file to `packages/core/docs/commercetools/changelog`.

Comment (MarcinSulowski) [reply packages/core/docs/changelog/6347.js]: will do, thanks!

**Review by filipsobol — APPROVED** [review]
