### PR TITLE
Bug/infinite loading

### LINKED ISSUE #5463: No shipping method in checkout
## Current behavior

1. Go to checkout as a guest, go to shipping, click "choose shipping method"
1. 

image

## Expected behavior

There should be a shipping method to choose

## Version of Vue Storefront

* [ ] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

### LINKED ISSUE #5508: Login/Register infinity loading
## Current behavior
After creating a second account with the same credentials or log in with wrong data we have an infinity loader and the `customerSignMeUp` request status all the time is `pending`

## Steps to reproduce the issue
1. Create an account
1. Logout
1. Create a second account with the same email / log in with the wrong credentials
1. You will see an infinity loader. After few minutes you have got Network Error

https://user-images.githubusercontent.com/40273258/107207973-3f090780-6a01-11eb-97ff-f859bc8a0fa3.mp4

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

### PR DESCRIPTION
**Pull request by Baroshem**
### Related Issues

closes #5508 
closes #5463 

### Short Description of the PR

Fixed problem with infinite loading caused by not having error handing in core/middleware. By implementing try catch, and throwing more accurate error in useUserFactory, now LoginModal is not closing after incorrect register/login attempt and it shows appropriate error. It also allowed to fix another problem related to empty shipping method when there was no shipping methods available.

### Screenshots of Visual Changes before/after (if There Are Any)

image

image

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [x] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

### CODE REVIEW

File: packages/core/core/src/factories/useUserFactory.ts [hunk 1]
```diff
@@ -63,7 +64,7 @@ export const useUserFactory = <USER, UPDATE_USER_PARAMS, REGISTER_USER_PARAMS ex
         user.value = await _factoryParams.register(providedUser);
         error.value.register = null;
       } catch (err) {
-        error.value.register = err;
+        error.value.register = err.response?.data || err;
```
Comment (andrzejewsky) [inline packages/core/core/src/factories/useUserFactory.ts:67]: just `err` - you can't assume graphql in the core

**Review by andrzejewsky — CHANGES_REQUESTED** [review]

File: packages/core/nuxt-theme-module/theme/components/LoginModal.vue [hunk 2]
```diff
@@ -210,19 +204,32 @@ export default {
...
 
-      const hasUserErrors = userError.value.register || userError.value.login;
+      const registerGraphQLError = userError.value.register?.response?.data;
+      const loginGraphQLError = userError.value.login?.response?.data;
+
+      const hasUserErrors = (registerGraphQLError || userError.value.register) || (loginGraphQLError || userError.value.login);
       if (hasUserErrors) {
-        error.login = userError.value.login;
-        error.register = userError.value.register;
+        const loginGraphQLErrorMessage = loginGraphQLError?.graphQLErrors[0]?.message;
```
Comment (andrzejewsky) [inline packages/core/nuxt-theme-module/theme/components/LoginModal.vue:228]: same here - this is core template

**Review by andrzejewsky — CHANGES_REQUESTED** [review]

File: packages/core/nuxt-theme-module/theme/components/LoginModal.vue (hunk 2 above)
Comment (Baroshem) [reply packages/core/nuxt-theme-module/theme/components/LoginModal.vue]: Moved error handling CT integration

**Review by filrak — APPROVED** [review]

**Review by andrzejewsky — APPROVED** [review]
